services:
  db:
    image: mysql:8.4
    container_name: simple-demo-db
    command: --ssl=0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demopass

    networks: 
      - keploy-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pdemopass"]
      interval: 5s
      retries: 10

networks:
  keploy-network:
    external: true 
    driver: bridge
